name: Tenable WAS Scan

on:
  push:
    branches:
      - main

jobs:
  was_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull Tenable WAS Scanner image
        run: docker pull tenable/was-scanner:latest

      - name: Run Tenable WAS Scan
        env:
          WAS_MODE: cicd
          ACCESS_KEY: ${{ secrets.TENABLE_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.TENABLE_SECRET_KEY }}
        run: |
          docker run -e WAS_MODE=$WAS_MODE -e ACCESS_KEY=$ACCESS_KEY -e SECRET_KEY=$SECRET_KEY \
          -v ${{ github.workspace }}:/scanner tenable/was-scanner:latest \
          

